# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopers < Formula
  desc "The Circuit Breaker for AI API Billing"
  homepage "https://tryloopers.com"
  version "2.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CURSED-ME/loopers-oss/releases/download/v2.13.0/loopers_Darwin_x86_64.tar.gz"
      sha256 "4dd10234843f7c441f1f4a6e0e55af21fbe60c13308e4986b5a8fb1259c81d46"

      define_method(:install) do
        bin.install "loopers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CURSED-ME/loopers-oss/releases/download/v2.13.0/loopers_Darwin_arm64.tar.gz"
      sha256 "bad84f115f22e8be866709eb2f469e12b16784fcafece5f9b3828b3ddb20c78c"

      define_method(:install) do
        bin.install "loopers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CURSED-ME/loopers-oss/releases/download/v2.13.0/loopers_Linux_x86_64.tar.gz"
      sha256 "fc14e92becf5e41952d7be8ad92be22ac52e0c652c467c64e927c816f9607e02"
      define_method(:install) do
        bin.install "loopers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CURSED-ME/loopers-oss/releases/download/v2.13.0/loopers_Linux_arm64.tar.gz"
      sha256 "514e49853f2f9a3565987d75768cecd70e540af5cf2875de7234c3ecf8442471"
      define_method(:install) do
        bin.install "loopers"
      end
    end
  end
end
